### ISSUE TITLE
Unable to send message to agent : No result found

### ISSUE THREAD

**Issue by lindhor** [skydive-project/skydive#1087]
In the analyzer logs I frequently see the message below.
```
2018-06-10T11:09:48.513Z    ERROR   client/client.go:158 (*OnDemandProbeClient).registerProbe   c49687828cfc: Unable to send message to agent : No result found
```
I start skydive in two separate containers, one for analyser and another for agent, i.e. not allinone. I also have a second node with agent only.

On the analyser these messages are logged at a rate of three log messages at the time. Each bunch come regularly every 1,30,1,30,1,30... seconds.

Anyone else have the same issue, knows the reason and possibly how to fix it? Guess it could be something in my config causing it?

I'm using the latest master version and have also tried latest released with same results.

**Comment by nplanel** [comment]
Hi @lindhor,

Could you provide us the Skydive configuration of both analyzer and agent ?

Thanks

**Comment by nplanel** [comment]
after a quick look/review, it seems the etcd is not configured correctly, at least in analyzer or agent.

```
etcd:
  # server parameters
  # when 'embedded' is set to true, the analyzer will start an embedded etcd server
  embedded: true
  listen: 0.0.0.0:2379

  servers:
    - http://skydive-roli-node1:12379

```

Obviously you should use the same port for listen and servers, I'm sure you understand the issue now.

If this not fixing you issue, could send us the agent/analyzer logs please.
