### ISSUE TITLE
ansible: support multi-threading

### ISSUE THREAD

**Issue by pierrecregut** [skydive-project/skydive#1484]
When skydive_node.py or skydive_edge.py are used in an ansible playbook, it is necessary to set --fork=1

**Comment by safchain** [comment]
can you give a example of a such playbook ?

**Comment by safchain** [comment]
what kind of error do you get without fork=1 ?

**Comment by pierrecregut** [comment]
It hangs. Here is the playbook. To use it, you can use any of the vagrant configurations from https://github.com/Juniper/vqfx10k-vagrant :

```yaml
---

- name: Skydive Ansible
  hosts: vqfx10k
  gather_facts: no
  connection: local
  tasks:

    - name: Collect device Facts and Configuration
      junos_facts:
        config_format: json
      register: result

    - name: Configuration in JSON (converted from XML)
      debug: var=result

    - name: Create TOR
      skydive_node:
        name: "{{ inventory_hostname }}"
        type: "fabric"
        metadata:
          Model:  "{{ result.ansible_facts.ansible_net_model }}"
      register: tor_result

    - name: Create ports
      skydive_node:
        name: "{{item.key}}"
        seed: "{{item.value.type}}-{{inventory_hostname}}-{{item.key}}"
        type: 'fabric'
        metadata:
          State: "{{item.value['oper-status'] | upper}}"
          MacAddress: "{{item.value.macaddress}}"
      register: port_result
      with_dict: "{{ result.ansible_facts.ansible_net_interfaces }}"

    - name: Link TOR and port
      skydive_edge:
        node1: "{{ tor_result.UUID }}"
        node2: "{{ item.UUID }}"
        relation_type: ownership
        metadata:
          Type: unknown
      loop: "{{port_result.results}}"
```
