### ISSUE TITLE
topoloy backend cannot set to elasticsearch

### ISSUE THREAD

**Issue by wat101** [skydive-project/skydive#1742]
When topology.backend is set to myelasticsearch, analyzer can start but not listen on port 8082. When topology.backend is set to mymemory, analyzer can start and listen on port 8082 properly.

Below is a snippet of my skydive.yml config.
```
analyzer:
  listen: 192.168.56.100:8082
  flow:
    backend: myelasticsearch
  topology:
    #backend: myelasticsearch
    backend: mymemory
storage:
  myelasticsearch:
    driver: elasticsearch
    host: 192.168.56.1001:9200
  mymemory:
    driver: memory
```
