### ISSUE TITLE
Ingress traffic is not getting collected by skydive when sending small/larger bytes

### ISSUE THREAD

**Issue by ajaysikdar** [skydive-project/skydive#2217]
We are seeing some issue with skydive agent.
In the case of ingress traffic, small/large bytes events are not getting collected by skydive agent.

Scenario-
1. cluster 1 - test-server pod  (skydive agent is running here)
2. cluster 2 - malicious server pod
3. 100000 bytes are sent from malicious server to test server pod.
4. We expect skydive agent should send event to cos as ingress traffic which is not happening.

Observation-
1. I can see bytes are received by the test server.
2. exporter is writing to cos without any error. Not seeing any error in the exporter log.
3. After sending bytes, I immediately check the exporter log about 2 min log and download the same log from the cos and check the IP and pod name.
  I am not seeing the IP and pod name in the downloaded object. I tried many times but still the same.
4. Tried to send bytes from test server to malicious server which is getting collected by skydive as egress traffic successfully.
5. Tried by sending small bytes, that also did not work.

bytes are send using nodejs script.
test server has exposed some api call to received bytes

```
var request = require('request');
const generateRandomBytes = (size) => {
    let result = '*';
    for (let i = 1; i < size; i++) {
        result += '*';
    }
    return result;
};
const data = generateRandomBytes(100000);
console.log(`sending data with length: ${data.length}`);
var options = {
    headers: { 'content-type': 'text/plain' },
    method: 'post',
    url: "http://<test_server_ip>:80/receive_data",
    body: data,
};
request(options, function (error, response, body) {
    console.log(body);
});
```

exporter starting log

```
ajays-MacBook-Pro:~ ajayk$ kubectl logs -f my-release-skydive-analyzer-8f4f78fbb-62xcv -n insight skydive-exporter
2020-05-20T09:10:00.508Z	INFO	pkg/classify_autodiscovery.go:43 getClusterNodesIPsWithRetries	: Querying Skydive analzyer topology for Kubenetes cluster nodes information
2020-05-20T09:10:15.547Z	ERROR	pkg/classify_autodiscovery.go:49 getClusterNodesIPsWithRetries	: Failed querying skydive analyzer (retrying): Post http://172.21.218.154:8082/api/topology: dial tcp 172.21.218.154:8082: connect: connection timed out
2020-05-20T09:10:16.562Z	INFO	pkg/classify_autodiscovery.go:37 NewClassifySubnetWithAutoDiscovery	: Adding Kubenetes cluster nodes net masks: []
2020-05-20T09:10:16.562Z	INFO	core/classify.go:103 NewClassifySubnetFromList	: Cluster net masks: []
2020-05-20T09:10:16.563Z	INFO	core/subscriber.go:60 NewSubscriber	: Subscribing to ws://my-release-skydive-service:8082/ws/subscriber/flow with namespace 'flow'
2020-05-20T09:10:16.567Z	INFO	websocket/client.go:511 (*Client).Connect	: Connecting to ws://my-release-skydive-service:8082/ws/subscriber/flow
2020-05-20T09:10:16.577Z	INFO	websocket/client.go:535 (*Client).Connect	: Connected to ws://my-release-skydive-service:8082/ws/subscriber/flow
2020-05-20T09:11:54.225Z	INFO	core/write_s3.go:55 (*writeS3).Write	: Wrote IBM/netflow/us-south/<cluster-id>/0/internal/20200520T091153Z/00000000.gz
2020-05-20T09:11:54.344Z	INFO	core/write_s3.go:55 (*writeS3).Write	: Wrote IBM/netflow/us-south/<cluster-id>/0/egress/20200520T091153Z/00000000.gz
2020-05-20T09:11:54.474Z	INFO	core/write_s3.go:55 (*writeS3).Write	: Wrote IBM/netflow/us-south/<cluster-id>/0/ingress/20200520T091153Z/00000000.gz
2020-05-20T09:12:53.776Z	INFO	core/write_s3.go:55 (*writeS3).Write	: Wrote IBM/netflow/us-south/<cluster-id>/0/internal/20200520T091153Z/00000001.gz
2020-05-20T09:12:53.984Z	INFO	core/write_s3.go:55 (*writeS3).Write	: Wrote IBM/netflow/us-south/<cluster-id>/0/egress/20200520T091153Z/00000001.gz
2020-05-20T09:12:54.000Z	INFO	core/write_s3.go:55 (*writeS3).Write	: Wrote IBM/netflow/us-south/<cluster-id>/0/ingress/20200520T091153Z/00000001.gz
2020-05-20T09:13:53.620Z	INFO	core/write_s3.go:55 (*writeS3).Write	: Wrote IBM/netflow/us-south/<cluster-id>/0/internal/20200520T091153Z/00000002.gz
2020-05-20T09:13:53.639Z	INFO	core/write_s3.go:55 (*writeS3).Write	: Wrote IBM/netflow/us-south/<cluster-id>/0/egress/20200520T091153Z/00000002.gz
```

**Comment by safchain** [comment]
can you please elaborate how you start the packet capture with Skydive, which probe, parameters ? thanks

**Comment by ajaykumar7-ibm** [comment]
Thanks @safchain for the quick response.
I used `ovsdb docker runc`
```
agent:
  topology:
    probes: "ovsdb docker runc"
```

This is the configuration I used, in case if you need more info on configuration related.
```
###############################################################################
############################ Skydive ##########################################
###############################################################################

##################
## Image variables
arch:
  amd64: "2 - No preference"
  ppc64le: "2 - No preference"
  s390x: "2 - No preference"

image:
  repository: skydive/skydive
  tag: "0.24.0"
  secretName: ""
  imagePullPolicy: IfNotPresent

##################
## Resources
resources:
  limits:
    cpu: 2000m
    memory: 8192Mi
  requests:
    cpu: 100m
    memory: 512Mi

##################
## Service variables
service:
  name: skydive
  port: 8082
  type: NodePort

etcd:
  port: 12379

analyzer:
  topology:
    fabric: "TOR1->*[Type=host]/eth0"

agent:
  topology:
    probes: "ovsdb docker runc"

## env variables
env: []

###################
## Elastic search image 
elasticsearch:
  image:
    repository: "elastic/elasticsearch"
    tag: "5.5.1"

##################
## Data / Storage
##
## - Persistence disables by default
persistence:
  enabled: false
  useDynamicProvisioning: false

dataVolume:
  name: "datavolume"
  existingClaimName: ""
  storageClassName: ""
  size: 10Gi

storage:
  flows:
    indicesToKeep: 10
    indexEntriesLimit: 10000
  topology:
    indicesToKeep: 10
    indexEntriesLimit: 10000
  elasticsearch:
    port: 9200
    host: 127.0.0.1

exporter:
  enabled: true
  image:
    repository: skydive/skydive-flow-exporter
    tag: 0.1.2
  store:
    bucket: ""
    objectPrefix: "IBM/netflow/us-south/<clusterid>/0"
    buffered:
      max_flows_per_object: 60000
  write:
    s3:
      #endpoint is a required value, pointing to a working Object Store endpoint Example value - "http://localhost:9000"
      endpoint: ""
      #installLocalMinio should be set to false if using an external endpoint. If set to true a default minio OS will be installed locally (in a container).
      #the below minioImage, minioImageTag - are rellevant only in case of installLocalMinio=true - for the default case for testing purposes
      installLocalMinio: false
      minioImage: "docker.io/bitnami/minio"
      minioImageTag: "2019.7.31-debian-9-r1"
      region: "us-south"
      # if use_api_key is set to true - api_key is a required value. Else fill in the access_key and secret_key
      use_api_key: true
      api_key: ""
      #the endpoint for api key validatation
      iam_endpoint: "https://iam.test.cloud.ibm.com/identity/token"
      # if use_api_key is set to false - fill in the rellevant access_key and secret_key of the used object store
      access_key: "admin"
      secret_key: "admin1234"

  env_exporter:
    # Maximum number of flows per object
    - name: SKYDIVE_PIPELINE_STORE_BUFFERED_MAX_FLOWS_PER_OBJECT
      value: "60000"

    # Maximum time period for object
    - name: SKYDIVE_PIPELINE_STORE_BUFFERED_MAX_SECONDS_PER_OBJECT
      value: "60"

    - name: SKYDIVE_PIPELINE_STORE_BUFFERED_MAX_FLOW_ARRAY_SIZE
      value: "100000"

    # New stream (folder) is opened every such period
    - name: SKYDIVE_PIPELINE_STORE_BUFFERED_MAX_SECONDS_PER_STREAM
      value: "86400"

    # to turn on autodiscovery of cluster netmasks use "subnet_autodiscovery" value; 
    # to turn off auto-discovery set the value to "subnet" (which is the default, in case SKYDIVE_PIPELINE_CLASSIFY_TYPE is not passed)
    - name: SKYDIVE_PIPELINE_CLASSIFY_TYPE
      value: "subnet_autodiscovery"

    # In case subnet_autodiscovery is set, value should include only the private netmasks.
    # if autodiscovery is off, set the value to the complete list of netmasks to be used
    - name: SKYDIVE_PIPELINE_CLASSIFY_CLUSTER_NET_MASKS
      value: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"

    - name: SKYDIVE_PIPELINE_MANGLE_TYPE
      value: "none"

    # exclude flows that are neither side is within our cluster. This mostly should not happen (because skydive records traffic in the cluster), but should
    # remove possible non-relevant flows. Other possible values (separated by spaces) internal , ingress , egress  (usually you don't want to exclude them).
    - name: SKYDIVE_PIPELINE_FILTER_EXCLUDED_TAGS
      value: "other"

    # This creates the toplevel data element necessary for security advisor data collector. Other possible values are json (array without the toplevel "data"  
    # element) and csv - but with other formats you can't connect to security advisor
    - name: SKYDIVE_PIPELINE_ENCODE_TYPE
      value: "secadvisor"

    # compresses type of uploaded objects. with gzip. Possible values gzip, none
    - name: SKYDIVE_PIPELINE_COMPRESS_TYPE
      value: "gzip"



  env:
    # For debug purposes
    - name: SKYDIVE_LOGGING_LEVEL
      value: "INFO"

    # the rate in which the agents transfer flow updates to the analyzer
    # Flows to be updated every 30 seconds (thus, every 60 seconds to defender)
    - name: SKYDIVE_FLOW_UPDATE
      value: "30"

    # ANALYZER_STARTUP_CAPTURE_GREMLIN invoke at startup capturing in selected nodes (sets automatic capture on all but he loopback nodes)
    - name: SKYDIVE_ANALYZER_STARTUP_CAPTURE_GREMLIN
      value: "G.V().has('Name', NE('lo'))"

    #capture all but skydive (8082)
    - name: SKYDIVE_ANALYZER_STARTUP_CAPTURE_BPF
      value: "not (tcp dst port 8082)"

    # DEFAULT_LAYER_KEY_MODE - the layers used to identify a unique flow.
    - name: SKYDIVE_FLOW_DEFAULT_LAYER_KEY_MODE
      value: "L3"

    # use pcap userland capture. Not very efficient but works on all linux kernel version
    - name: SKYDIVE_ANALYZER_STARTUP_CAPTURE_TYPE
      value: "pcap"

    - name: SKYDIVE_AGENT_CAPTURE_SYN
      value: "True"

```
