### ISSUE TITLE
Skydive and Netflow without OVS?

### ISSUE THREAD

**Issue by m8522s** [skydive-project/skydive#2379]
Hi team,

just a question: can I run the skydive agent _with_ Netflow but _without_ OVS?
My config includes a simple netflow stanza, the agent starts fine and is visible in the analyzer's web UI. 

```
agent:
  flow:
    netflow:
      bind_address: 127.0.0.1
      port_min: 2055
      port_max: 2056
```
However, there is no process binding to localhost on that port and the output of skydive is:
`Jul 14 10:46:54 cazzdf skydive[81832]: 2021-07-14T10:46:54.251+0200        ERROR        agent/flow_probes.go:84 NewFlowProbeBundle        cazzdf: Failed to create ovsnetflow probe: ovsnetflow probe depends on ovsdb topology probe, probe can't start properly`

So I am wondering if skydive requires ovsdb to enable Netflow.
Thanks for you comments.
