### ISSUE TITLE
Failed to create analyzer: not implemented

### ISSUE THREAD

**Issue by amwork2020** [skydive-project/skydive#2407]
1. skydive 0.28.0
2. docker run -d --name elasticsearch -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.14.2
3. skydive.yml
```
analyzers:
  - 192.168.68.21:8082

agent:
  listen: 0.0.0.0:8081
  topology:
    probes:
      - ovsdb

analyzer:
  listen: 192.168.68.21:8082
  topology:
    backend: myelasticsearch
    probes:
      - ovn
    ovn:
      address: unix:/run/ovn/ovnnb_db.sock

storage:
  myelasticsearch:
    driver: elasticsearch
    host: 192.168.68.21:9200

etcd:
  embedded: true
  listen: 192.168.68.21:12379

```
**skydive -c skydive.yml allinone**

2021-11-22T21:11:58.762+0800	INFO	analyzer/analyzer.go:42 glob..func1	ovn1: Skydive Analyzer 0.28.0 starting...
2021-11-22T21:11:58.763+0800	INFO	analyzer/storage.go:74 newGraphBackendFromConfig	ovn1: Using myelasticsearch (driver elasticsearch) as graph storage backend
2021-11-22T21:11:58.764+0800	INFO	plugin/topology.go:47 LoadTopologyPlugins	ovn1: Topology plugins: []
**_Failed to create analyzer: not implemented_**
2021-11-22T21:12:50.278+0800	ERROR	allinone/allinone.go:131 glob..func1	ovn1: Failed to start Skydive analyzer: All attempts fail:
#1: Get "http://192.168.68.21:8082/api": dial tcp 192.168.68.21:8082: connect: connection refused
#2: Get "http://192.168.68.21:8082/api": dial tcp 192.168.68.21:8082: connect: connection refused
#3: Get "http://192.168.68.21:8082/api": dial tcp 192.168.68.21:8082: connect: connection refused
#4: Get "http://192.168.68.21:8082/api": dial tcp 192.168.68.21:8082: connect: connection refused
#5: Get "http://192.168.68.21:8082/api": dial tcp 192.168.68.21:8082: connect: connection refused
#6: Get "http://192.168.68.21:8082/api": dial tcp 192.168.68.21:8082: connect: connection refused
#7: Get "http://192.168.68.21:8082/api": dial tcp 192.168.68.21:8082: connect: connection refused
#8: Get "http://192.168.68.21:8082/api": dial tcp 192.168.68.21:8082: connect: connection refused
#9: Get "http://192.168.68.21:8082/api": dial tcp 192.168.68.21:8082: connect: connection refused
#10: Get "http://192.168.68.21:8082/api": dial tcp 192.168.68.21:8082: connect: connection refused

but when I used skydive 0.27.0 it work fine!
when I "  # -ovn  " it work fine, but I want to use ovn, what's wrong?
help! Thanks a lot!
