### ISSUE TITLE
etcd: enable clustering when behind proxy

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive#798]
In the scenario when we want to connect two analyzers as follows:

analyzer (client) ----> proxy ----> analyzer (server)

To support this the following enhancements are needed

(1)
Analyzer (client) needs to be able to set per peer crenetials:

```
etcd:
  client:
    peers:
    - analyzer1:
         url: [http|https]://<proxy-address>:<port>
         user: <user>
         password: <password>
         cookie:
           <key1>: <value1>
           <key2>: <value2>
```
(2)
Analyzer (server) can set address(s) it advertises (when a client connects to it):

```
etcd:
  server:
    advertise: [http|https]//:<proxy-address>:<port>
```

(3)
Analyzer (server) can set both client and peer (default is client+1) ports

```
etcd:
  server:
    listen:
     client: <port>
     peer: <port>
```
